services:
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ../crawl-data-exp1:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ROOT_PASSWORD: jeanluc
      MYSQL_DATABASE: crawl
    ports:
      - "3306:3306"

  crawler:
    container_name: crawler_jeanluc
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mysql_db
    volumes:
      - ../crawl-files-exp1/:/usr/app/data_content/
    environment:
      - BASE_DIR=/usr/app/data_content/
      - APP_DIR=/usr/app/
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=jeanluc
      - DB_NAME=crawl

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8184:80
