version: "3.1"
services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ../crawl-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: jeanluc
      MYSQL_DATABASE: crawl

  crawler:
    container_name: crawler_jeanluc
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mysql_db
    volumes:
      - ../crawl-files/:/usr/app/data_content/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8184:80
